In [1]:
import numpy as np

In [4]:
OneDarray = np.array([1, 2, 3, 4, 5, 6])     # مصفوفه ذو بعد واحد
print(OneDarray)

[1 2 3 4 5 6]


In [6]:
print(OneDarray.ndim)  # معرفه ابعاد المصفوفه

1


In [7]:
TwoDarray =np.array([[1, 2, 3, 4], [5, 6, 7, 8]])    #مصفوفه ذو بعدين 
print(TwoDarray)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
print(TwoDarray.ndim)   # معرفه ابعاد المصفوفه

2


In [11]:
ThreeDarray = np.array([[[1, 2, 3], [-1, -2, -3]], [[4, 5, 6], [-4, -5, -6]]]) #مصفوفه ذو ثلاث ابعاد 
print(ThreeDarray)

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


In [10]:
print(ThreeDarray.ndim)   # معرفه ابعاد المصفوفه

3


In [12]:
# indexing 
#examples
# find num 5 in TwoDarray or ThreeDarray

In [13]:
#in TwoDarray
print(TwoDarray[1])

[5 6 7 8]


In [14]:
print(TwoDarray[1, 0])

5


In [15]:
#in ThreeDarray 
print(ThreeDarray[1])

[[ 4  5  6]
 [-4 -5 -6]]


In [16]:
print(ThreeDarray[1, 0])

[4 5 6]


In [17]:
print(ThreeDarray[1, 0, 1])

5


In [18]:
# shape the array
print(TwoDarray.shape)

(2, 4)


In [19]:
# shape the array
print(ThreeDarray.shape)

(2, 2, 3)


In [21]:
#iterating over numpy arrays
for i in TwoDarray:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [22]:
for i in TwoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


In [23]:
for i in ThreeDarray:
    print(i)

[[ 1  2  3]
 [-1 -2 -3]]
[[ 4  5  6]
 [-4 -5 -6]]


In [24]:
for i in ThreeDarray:
    for j in i:
        print(j)

[1 2 3]
[-1 -2 -3]
[4 5 6]
[-4 -5 -6]


In [25]:
for i in ThreeDarray:    #outermost of loop
    for j in i:          #second for loop
        for k in j:      #third for loop
            print(k)

1
2
3
-1
-2
-3
4
5
6
-4
-5
-6


In [26]:
#zeros array

ZerosArray = np.zeros(10)  #result is float         #10 >>>>>>> Number of items within the matrix
print(ZerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
# to convert an array of float into integer
ZerosArray = ZerosArray.astype(int)
print(ZerosArray)

[0 0 0 0 0 0 0 0 0 0]


In [28]:
#ones array
ones_array = np.ones(10)    #10 >>>>>>> Number of items within the matrix
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [29]:
# to convert an array of float into integer
ones_array = ones_array.astype(int)
print(ones_array)

[1 1 1 1 1 1 1 1 1 1]


In [30]:
#full array
PreFillArray = np.full(10,5)  #10 >>>>>>> Number of items within the matrix
print(PreFillArray)           

[5 5 5 5 5 5 5 5 5 5]


In [38]:
# Adding or subtracting a scaler in matrix 
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

print('#' * 50)

print(matrix + 2)    # Adding 

print('#' * 50)

print(matrix - 2)

[[1 2 3]
 [4 5 6]]
##################################################
[[3 4 5]
 [6 7 8]]
##################################################
[[-1  0  1]
 [ 2  3  4]]


In [39]:
# Adding or subtracting a scaler in python list  give error

python_list = [[1, 2, 3], [4, 5, 6]]    
print(python_list)

print('#' * 50)

print(python_list + 2)      #>>>>>>>>>>>>>>> Error

print('#' * 50)

print(python_list - 2)      #>>>>>>>>>>>>>>> Error

[[1, 2, 3], [4, 5, 6]]
##################################################


TypeError: can only concatenate list (not "int") to list

In [40]:
#multiplying by a scaler in matrix
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [41]:
#multiplying by a scaler in python list 
print(python_list * 2)           

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [42]:
#Dividing by a scaler in matrix
print(matrix / 2)   #float

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [43]:
print(matrix // 2)  # int

[[0 1 1]
 [2 2 3]]


In [44]:
#Dividing by a scaler in python list 
print(python_list / 2)   # error

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [45]:
# raise to a power 
print(matrix ** 2)

[[ 1  4  9]
 [16 25 36]]


In [46]:
print(python_list** 2)      #error

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [50]:
#Transpose the matrix
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [48]:
#Transpose python list
print(python_list.T)     #error

AttributeError: 'list' object has no attribute 'T'

In [54]:
# element wise addtion 
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [55]:
matrix2 = np.array([[-1, -2, -3], [-4, -5, -6]])
print(matrix2)

[[-1 -2 -3]
 [-4 -5 -6]]


In [56]:
print(matrix1 + matrix2)

[[0 0 0]
 [0 0 0]]


In [58]:
pythonlist1 = [[1, 2, 3], [4, 5, 6]]
pythonlist2 = [[-1, -2, -3], [-4, -5, -6]]
print(pythonlist1 + pythonlist2)   # concatination 

[[1, 2, 3], [4, 5, 6], [-1, -2, -3], [-4, -5, -6]]


In [59]:
# element wise subtraction
print(matrix1 - matrix2)

[[ 2  4  6]
 [ 8 10 12]]


In [60]:
print(pythonlist1 - pythonlist2)    #error

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [61]:
# element wise multiplication 
print(matrix1 * matrix2)

[[ -1  -4  -9]
 [-16 -25 -36]]


In [62]:
print(pythonlist1 * pythonlist2)  #error

TypeError: can't multiply sequence by non-int of type 'list'

In [63]:
# element wise division
print(matrix1 / matrix2)  #float

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [64]:
print(matrix1 // matrix2)  # int

[[-1 -1 -1]
 [-1 -1 -1]]


In [65]:
print(pythonlist1 / pythonlist2)  # error

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [73]:
np.nditer(matrix1)

(2, 3)


(2, 3)
